---

- name: Install package
  pkgng: name=py27-fail2ban

- name: Protect sshd
  template:
    src: sshd.local.j2
    dest: /usr/local/etc/fail2ban/jail.d/sshd.local
  notify: reload fail2ban

- name: Enabling service
  sysrc: name="fail2ban_enable" value="YES"
  when: fail2ban_enable == "yes"

- name: Start service
  service: name="fail2ban" state="started"
  when: fail2ban_enable == "yes"
